run:
  timeout: 2m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gocritic
    - revive
    - misspell
    - gofmt
    - goimports
